import Footer from "@/components/Footer";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Inter } from "next/font/google";
import localFont from "next/font/local";


const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-inter",
});


const graphik = localFont({
  src: "../assets/font/GraphikCondensed-Black-Trial.otf",
   weight: '900',
  variable: "--font-graphik",
});

export const metadata = {
  title: "Software Chamber",
  description: "Generated by Tahazzee",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={`${inter.variable} ${graphik.variable}`}>
         <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
